### ISSUE TITLE
error during ./configure

### ISSUE THREAD

**Issue by visbs** [chenbd/miracle#2]
this is what i get while compilation
No package 'libwfd' found
No package 'libsystemd-daemon' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

**Comment by visbs** [comment]
No package 'libsystemd-daemon' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables DEPS_CFLAGS
and DEPS_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
-----------------------------------------------------------------------------------------------
okay previously i didn't install libwfd so that was my mistake but now i have installed libsystemd but still this error is there need some suggestions...
TIA

**Comment by chenbd** [comment]
@visbs I'm not maintain this code, guess you can look into https://github.com/albfan/miraclecast
